# Generated by Django 4.2.11 on 2026-02-26 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='bookingDate',
            new_name='booking_date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='releaseDate',
            new_name='release_date',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='bookingStatus',
            new_name='booking_status',
        ),
        migrations.RenameField(
            model_name='seat',
            old_name='seatNumber',
            new_name='seat_number',
        ),
    ]
